package render_test

import (
	"strings"
	"testing"

	"sigs.k8s.io/yaml"

	"github.com/duynhlab/obs-as-code/internal/folders"
	"github.com/duynhlab/obs-as-code/internal/profile"
	"github.com/duynhlab/obs-as-code/internal/render"
)

// decode renders obj and unmarshals it into a generic map, so assertions are
// made against the bytes that actually ship rather than against Go structs
// agreeing with themselves.
func decode(t *testing.T, obj render.Object) map[string]any {
	t.Helper()

	out, err := obj.YAML()
	if err != nil {
		t.Fatalf("YAML() error = %v", err)
	}
	if !strings.HasPrefix(string(out), "# Generated by obs-as-code") {
		t.Error("YAML() output has no generated-file header")
	}

	var got map[string]any
	if err := yaml.Unmarshal(out, &got); err != nil {
		t.Fatalf("yaml.Unmarshal() error = %v\n%s", err, out)
	}
	return got
}

func dig(t *testing.T, m map[string]any, path ...string) any {
	t.Helper()

	var cur any = m
	for i, key := range path {
		asMap, ok := cur.(map[string]any)
		if !ok {
			t.Fatalf("path %v: %q is not a map", path[:i], path[i-1])
		}
		cur, ok = asMap[key]
		if !ok {
			t.Fatalf("path %v: key %q is absent", path[:i+1], key)
		}
	}
	return cur
}

func TestFolder(t *testing.T) {
	t.Parallel()

	p := profile.Cluster()
	obj, err := render.Folder(p, folders.Examples)
	if err != nil {
		t.Fatalf("Folder() error = %v", err)
	}

	if got, want := obj.Kind, "GrafanaFolder"; got != want {
		t.Errorf("Kind = %q, want %q", got, want)
	}
	if got, want := obj.Path(), "grafanafolder/obs-as-code-examples.yaml"; got != want {
		t.Errorf("Path() = %q, want %q", got, want)
	}

	got := decode(t, obj)

	if v, want := dig(t, got, "apiVersion"), "grafana.integreatly.org/v1beta1"; v != want {
		t.Errorf("apiVersion = %v, want %q", v, want)
	}
	if v, want := dig(t, got, "metadata", "namespace"), "monitoring"; v != want {
		t.Errorf("metadata.namespace = %v, want %q", v, want)
	}
	if v, want := dig(t, got, "spec", "uid"), folders.Examples.UID; v != want {
		t.Errorf("spec.uid = %v, want %q", v, want)
	}
	if v, want := dig(t, got, "spec", "title"), folders.Examples.Title; v != want {
		t.Errorf("spec.title = %v, want %q", v, want)
	}

	// GrafanaCommonSpec is embedded anonymously; if Go stopped promoting its
	// fields the operator would silently never match an instance.
	if v, want := dig(t, got, "spec", "instanceSelector", "matchLabels", "dashboards"), "grafana"; v != want {
		t.Errorf("spec.instanceSelector.matchLabels.dashboards = %v, want %q", v, want)
	}
	if v, want := dig(t, got, "spec", "resyncPeriod"), "30s"; v != want {
		t.Errorf("spec.resyncPeriod = %v, want %q", v, want)
	}
	if v := dig(t, got, "spec", "allowCrossNamespaceImport"); v != true {
		t.Errorf("spec.allowCrossNamespaceImport = %v, want true", v)
	}
}

func TestFolderRejectsBadInput(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		profile profile.Profile
		folder  folders.Folder
		wantErr string
	}{
		{
			name:    "invalid folder uid",
			profile: profile.Cluster(),
			folder:  folders.Folder{UID: "Bad_UID", Title: "T"},
			wantErr: "DNS-1123",
		},
		{
			name:    "empty folder title",
			profile: profile.Cluster(),
			folder:  folders.Folder{UID: "ok"},
			wantErr: "title is empty",
		},
		{
			name:    "invalid profile",
			profile: profile.Profile{},
			folder:  folders.Examples,
			wantErr: "invalid profile",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			_, err := render.Folder(tt.profile, tt.folder)
			if err == nil {
				t.Fatalf("Folder() = nil error, want one containing %q", tt.wantErr)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("Folder() error = %v, want it to contain %q", err, tt.wantErr)
			}
		})
	}
}
