// Package render turns built Grafana models into Grafana Operator custom
// resources.
//
// The resource structs here are hand-written rather than imported from
// github.com/grafana/grafana-operator/v5/api/v1beta1, which would drag in
// apimachinery and controller-runtime for a handful of fields. The cost of
// hand-writing them is that they can drift from the CRDs the cluster actually
// has installed, so `make validate` checks generated output against the real
// CRD OpenAPI schemas with kubeconform, and the integration test runs a
// server-side dry-run. Both are stronger checks than compile-time types, which
// only prove the structs agree with themselves.
package render

import (
	"fmt"
	"strings"

	"sigs.k8s.io/yaml"
)

// APIVersion is the Grafana Operator API group this package emits. The cluster
// runs operator 5.24.0, which serves v1beta1 only.
const APIVersion = "grafana.integreatly.org/v1beta1"

// header is prepended to every emitted file. Someone will eventually find one
// of these in a git blame or a kubectl diff and needs to know not to edit it.
const header = `# Generated by obs-as-code — DO NOT EDIT.
# Source: https://github.com/duynhlab/obs-as-code
# Regenerate with: make generate
`

// Object is one rendered Kubernetes resource, ready to be written to disk.
//
// Construct one with Dashboard, AlertRuleGroup or Folder; the zero Object
// marshals to nothing useful.
type Object struct {
	// Kind is the resource kind, e.g. "GrafanaDashboard".
	Kind string

	// Name is metadata.name, and also the output file's base name.
	Name string

	// Namespace is metadata.namespace.
	Namespace string

	// body is the typed resource struct. Unexported so an Object cannot be
	// assembled with a body that disagrees with Kind and Name.
	body any
}

// YAML renders o as a single YAML document with the generated-file header.
func (o Object) YAML() ([]byte, error) {
	if o.body == nil {
		return nil, fmt.Errorf("render: %s/%s has no body", o.Kind, o.Name)
	}

	out, err := yaml.Marshal(o.body)
	if err != nil {
		return nil, fmt.Errorf("render: marshal %s/%s: %w", o.Kind, o.Name, err)
	}

	return append([]byte(header), out...), nil
}

// Path is o's location beneath a profile's output directory, e.g.
// "grafanadashboard/envoy-edge.yaml".
//
// Grouping by kind rather than by Grafana folder keeps one file per resource,
// gives folder resources somewhere to live, and sorts predictably — all three
// matter once the tree holds fifty boards and a reviewer is reading a diff.
func (o Object) Path() string {
	return strings.ToLower(o.Kind) + "/" + o.Name + ".yaml"
}

// objectMeta is the subset of metav1.ObjectMeta this repo sets.
type objectMeta struct {
	Name        string            `json:"name"`
	Namespace   string            `json:"namespace,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// labelSelector is the subset of metav1.LabelSelector the operator reads from
// spec.instanceSelector.
type labelSelector struct {
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
}

// commonSpec is GrafanaCommonSpec, inlined into every resource spec.
//
// InstanceSelector carries no omitempty on purpose: the CRD declares it
// required, and an operator that cannot match an instance ignores the resource
// silently rather than reporting an error.
type commonSpec struct {
	ResyncPeriod              string        `json:"resyncPeriod,omitempty"`
	InstanceSelector          labelSelector `json:"instanceSelector"`
	AllowCrossNamespaceImport bool          `json:"allowCrossNamespaceImport,omitempty"`
}
