// Package common composes dashboard V2 resources with the project's defaults.
package common

import (
	"fmt"

	"github.com/grafana/grafana-foundation-sdk/go/cog"
	"github.com/grafana/grafana-foundation-sdk/go/dashboardv2"

	"github.com/duynhlab/obs-as-code/internal/panels"
	"github.com/duynhlab/obs-as-code/internal/profile"
	"github.com/duynhlab/obs-as-code/internal/registry"
)

// Tag identifies dashboards generated by this repository.
const Tag = "obs-as-code"

type row struct {
	title  string
	panels []placedPanel
}

type placedPanel struct {
	key   string
	panel *panels.Panel
}

// DashboardBuilder keeps V2 elements and their separate layout references in
// one API, so dashboard authors cannot accidentally update only one side.
type DashboardBuilder struct {
	sdk    *dashboardv2.DashboardBuilder
	rows   []row
	links  []cog.Builder[dashboardv2.DashboardLink]
	keys   map[string]bool
	errors []error
	nextID float64
}

// NewDashboard applies every house default and the profile datasource variable.
func NewDashboard(p profile.Profile, m registry.Meta, tags ...string) *DashboardBuilder {
	allTags := append([]string{Tag, m.OwnerTag()}, tags...)
	b := &DashboardBuilder{
		sdk: dashboardv2.NewDashboardBuilder(m.Title).
			Tags(allTags).
			Editable(true).
			CursorSync(dashboardv2.DashboardCursorSyncCrosshair).
			TimeSettings(dashboardv2.NewTimeSettingsBuilder().
				Timezone("browser").
				From("now-6h").
				To("now").
				AutoRefresh("1m").
				AutoRefreshIntervals([]string{"30s", "1m", "5m", "15m", "1h"})).
			DatasourceVariable(p.MetricsVariable()),
		keys:   make(map[string]bool),
		nextID: 1,
	}
	b.links = append(b.links, dashboardv2.NewDashboardLinkBuilder().
		Title("Generated from code — edits here are overwritten").
		Type(dashboardv2.DashboardLinkTypeLink).
		Icon("code-branch").
		TargetBlank(true).
		Url(p.SourceURL))
	return b
}

// QueryVariable appends a query variable.
func (b *DashboardBuilder) QueryVariable(v *dashboardv2.QueryVariableBuilder) *DashboardBuilder {
	b.sdk.QueryVariable(v)
	return b
}

// Link appends a dashboard link.
func (b *DashboardBuilder) Link(link *dashboardv2.DashboardLinkBuilder) *DashboardBuilder {
	b.links = append(b.links, link)
	return b
}

// Row starts a new visible row.
func (b *DashboardBuilder) Row(title string) *DashboardBuilder {
	b.rows = append(b.rows, row{title: title})
	return b
}

// Panel adds a keyed panel to the current row.
func (b *DashboardBuilder) Panel(key string, panel *panels.Panel) *DashboardBuilder {
	if len(b.rows) == 0 {
		b.errors = append(b.errors, fmt.Errorf("panel %q has no row", key))
		return b
	}
	if key == "" {
		b.errors = append(b.errors, fmt.Errorf("panel element key is empty"))
		return b
	}
	if b.keys[key] {
		b.errors = append(b.errors, fmt.Errorf("panel element key %q is duplicated", key))
		return b
	}
	b.keys[key] = true
	idx := len(b.rows) - 1
	b.rows[idx].panels = append(b.rows[idx].panels, placedPanel{key: key, panel: panel})
	return b
}

// Build creates a validated dashboard V2 spec.
func (b *DashboardBuilder) Build() (dashboardv2.Dashboard, error) {
	if len(b.errors) > 0 {
		return dashboardv2.Dashboard{}, fmt.Errorf("compose dashboard: %v", b.errors)
	}

	rows := dashboardv2.NewRowsBuilder()
	for _, sourceRow := range b.rows {
		grid := dashboardv2.NewGridBuilder()
		var x, y, lineHeight int64
		for _, placed := range sourceRow.panels {
			width, height := placed.panel.Width(), placed.panel.GridHeight()
			if width < 1 || width > 24 || height < 1 {
				return dashboardv2.Dashboard{}, fmt.Errorf("compose dashboard: panel %q has invalid size %dx%d", placed.key, width, height)
			}
			if x+width > 24 {
				x = 0
				y += lineHeight
				lineHeight = 0
			}
			b.sdk.Panel(placed.key, placed.panel.Build(b.nextID))
			b.nextID++
			grid.Item(dashboardv2.GridItem(placed.key).X(x).Y(y).Width(width).Height(height))
			x += width
			if height > lineHeight {
				lineHeight = height
			}
		}
		rows.Row(dashboardv2.Row(sourceRow.title).GridLayout(grid))
	}
	b.sdk.RowsLayout(rows).Links(b.links)
	return b.sdk.Build()
}
